single_keypoint_tracking_node:
  ros__parameters:

    input_keypoints_topic_name: "posenet/keypoints"
    input_keypoints_topic_queue_size: 100

    output_keypoints_topic_name: "filtered_keypoints"
    output_keypoints_topic_queue_size: 10

    keypoint_name: "right_shoulder"
    tracking_window_width: 0.2
    tracking_window_height: 0.2
    timer_period: 0.01
    moving_average_window_size: 10

    initial_state: [0.5, 0.5, 0.0, 0.0]
    covariances: [1.0, 1.0, 1.0, 1.0]
    process_noises: [0.1, 0.1, 0.001, 0.001]
    observation_noises: [0.01, 0.01]
